### ISSUE TITLE
WKWebView scrollView contentSize

### ISSUE THREAD

**Issue by ethanguan26** [ShingoFukuyama/WKWebViewTips#13]
Thanks for your tips!
I have a question that how to get a correct contentSize of WKWebView?
In my project, I use WKWebView to load some local html string.after loading,I wish the webView would   fit the size automatic.But, sometimes I got a wrong size,the webView's contentSize height longer than the content real height.
Can you give me some suggestion to solve it?
Thanks!

**Comment by ShingoFukuyama** [comment]
I guess the culprit is `shrink-to-fit`.

> Viewport meta tags using "width=device-width" cause the page to scale down to fit content that overflows the viewport bounds. You can override this behavior by adding "shrink-to-fit=no" to your meta tag as shown below. The added value will prevent the page from scaling to fit the viewport.
> 
> ```
> <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
> ```

[Safari iOS 9.0](https://developer.apple.com/library/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_0.html#//apple_ref/doc/uid/TP40014305-CH9-SW36)

I manage this unwanted behavior force to rewrite or add `shrink-to-fit` `no` by user script injection at the end of document load.

Other possibilities:
- invisible elements taken up space.
- webView's scrollView contentInset property modified.

**Comment by ethanguan26** [comment]
Thanks for your response!
